# Generated by Django 5.2.17 on 2026-08-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='jobs/input/'),
        ),
    ]
