services:
  db:
    image: postgres:16
    container_name: jobflow_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: jobflow
      POSTGRES_USER: jobflow_user
      POSTGRES_PASSWORD: jobflow_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: