import { useRef, useState } from "react";
import type { ChangeEvent, DragEvent, FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import { createJob } from "../services/jobs";
import type { JobPriority } from "../types/job";

export default function CreateJob() {
  const navigate = useNavigate(); const inputRef = useRef<HTMLInputElement>(null);
  const [file, setFile] = useState<File | null>(null); const [priority, setPriority] = useState<JobPriority>("MEDIUM"); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [dragging, setDragging] = useState(false);
  const choose = (candidate: File | undefined) => { if (!candidate) return; if (!candidate.name.toLowerCase().endsWith(".csv")) { setError("Please choose a CSV file."); return; } setError(""); setFile(candidate); };
  const onDrop = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); setDragging(false); choose(event.dataTransfer.files[0]); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!file) { setError("Choose a CSV file before creating the job."); return; } setLoading(true); setError(""); try { const job = await createJob({ job_type: "CSV_ANALYSIS", priority, input_file: file }); navigate(`/jobs/${job.id}`); } catch { setError("The job could not be created. Check the file and try again."); } finally { setLoading(false); } };
  return <div className="page narrow-page"><header className="page-header"><div><Link className="back-link" to="/jobs">← All jobs</Link><p className="eyebrow">NEW WORKFLOW</p><h1>Create a job</h1><p className="muted">Upload a CSV and let JobFlow handle the analysis.</p></div></header><form className="content-panel form-panel" onSubmit={submit}><label>Job type<div className="static-field"><strong>CSV analysis</strong><span>CSV</span></div></label><label>Priority<select value={priority} onChange={(event: ChangeEvent<HTMLSelectElement>) => setPriority(event.target.value as JobPriority)}><option value="HIGH">High</option><option value="MEDIUM">Medium</option><option value="LOW">Low</option></select></label><div className={`drop-zone ${dragging ? "is-dragging" : ""}`} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={onDrop} onClick={() => inputRef.current?.click()}><input ref={inputRef} type="file" accept=".csv,text/csv" hidden onChange={(event) => choose(event.target.files?.[0])} />{file ? <><span className="file-icon">CSV</span><strong>{file.name}</strong><span className="muted">{(file.size / 1024).toFixed(1)} KB · Click to replace</span></> : <><span className="upload-icon">↑</span><strong>Drop your CSV here</strong><span className="muted">or click to browse · CSV files only</span></>}</div>{file && <button type="button" className="text-button" onClick={() => setFile(null)}>Remove file</button>}{error && <div className="alert alert-error">{error}</div>}<div className="form-actions"><Link className="secondary-button" to="/jobs">Cancel</Link><button className="primary-button" disabled={loading}>{loading ? "Creating..." : "Create job →"}</button></div></form></div>;
}
