import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import ProgressBar from "../components/ProgressBar";
import { ErrorState, LoadingState } from "../components/PageState";
import StatusBadge from "../components/StatusBadge";
import { cancelJob, getJob } from "../services/jobs";
import type { Job } from "../types/job";

const active = ["QUEUED", "PROCESSING", "RETRYING"];
const formatDate = (value: string) => new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" });
export default function JobDetails() {
  const { id = "" } = useParams(); const [job, setJob] = useState<Job | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [cancelling, setCancelling] = useState(false);
  useEffect(() => { let timer: number | undefined; let disposed = false; const load = async () => { try { const data = await getJob(id); if (!disposed) { setJob(data); if (active.includes(data.status)) timer = window.setTimeout(load, 3000); } } catch { if (!disposed) setError("We could not load this job."); } }; void load(); return () => { disposed = true; if (timer) window.clearTimeout(timer); }; }, [id]);
  const cancel = async () => { if (!job || !window.confirm(`Cancel job #${job.id}?`)) return; setCancelling(true); setMessage(""); try { await cancelJob(job.id); setJob(await getJob(id)); setMessage("Cancellation requested."); } catch { setError("This job could not be cancelled."); } finally { setCancelling(false); } };
  if (error && !job) return <div className="page"><ErrorState message={error} /></div>; if (!job) return <div className="page"><LoadingState label="Loading job..." /></div>;
  return <div className="page narrow-page"><header className="page-header"><div><Link className="back-link" to="/jobs">← All jobs</Link><p className="eyebrow">JOB #{job.id}</p><h1>{job.job_type.replaceAll("_", " ")}</h1><p className="muted">Created {formatDate(job.created_at)}</p></div><div className="header-actions"><StatusBadge status={job.status} />{active.includes(job.status) && <button className="secondary-button danger-button" disabled={cancelling} onClick={cancel}>{cancelling ? "Cancelling..." : "Cancel job"}</button>}</div></header>{message && <div className="alert alert-success">{message}</div>}{error && <ErrorState message={error} />}<section className="detail-progress content-panel"><div className="detail-progress-head"><div><span className="eyebrow">PROCESSING PROGRESS</span><h2>{job.status === "SUCCESS" ? "Analysis complete" : job.status === "FAILED" ? "Analysis failed" : "Working on it"}</h2></div><strong className="big-progress">{job.progress}%</strong></div><ProgressBar value={job.progress} /></section><section className="details-grid content-panel"><div><span className="detail-label">Job ID</span><strong>#{job.id}</strong></div><div><span className="detail-label">Priority</span><strong>{job.priority}</strong></div><div><span className="detail-label">Created</span><strong>{formatDate(job.created_at)}</strong></div><div><span className="detail-label">Last updated</span><strong>{formatDate(job.updated_at)}</strong></div><div><span className="detail-label">Input file</span><strong>{job.input_file ? job.input_file.split("/").pop() : "Not available"}</strong></div></section>{job.result && <section className="result-panel content-panel"><div className="section-heading"><div><p className="eyebrow">OUTPUT</p><h2>CSV analysis result</h2></div></div><div className="result-grid"><div><span>Rows</span><strong>{job.result.rows}</strong></div><div><span>Columns</span><strong>{job.result.columns}</strong></div><div><span>Missing values</span><strong>{job.result.missing_values}</strong></div><div><span>Duplicate rows</span><strong>{job.result.duplicate_rows}</strong></div></div><p className="muted result-file">{job.result.file_name} · {job.result.column_names.join(", ")}</p></section>}{job.attempts && job.attempts.length > 0 && <section className="attempts"><p className="eyebrow">EXECUTION HISTORY</p>{job.attempts.map((attempt) => <div className="attempt-row" key={attempt.attempt_number}><span>Attempt {attempt.attempt_number}</span><StatusBadge status={attempt.status} /><span className="muted">{attempt.error_message || "Completed without errors"}</span></div>)}</section>}</div>;
}
